# Generated by Django 4.2 on 2025-11-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mas', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie_mas', models.CharField(max_length=50, unique=True)),
                ('nombre_mas', models.CharField(max_length=100)),
                ('especie_mas', models.CharField(max_length=50)),
                ('raza_mas', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo_mas', models.CharField(max_length=10)),
                ('edad_mas', models.PositiveIntegerField()),
                ('peso_mas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto_mas', models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/')),
                ('historial_mas', models.TextField(blank=True, null=True)),
                ('estado_mas', models.CharField(max_length=20)),
                ('fecha_registro_mas', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_per', models.CharField(max_length=100)),
                ('apellido_per', models.CharField(max_length=100)),
                ('telefono_per', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_per', models.EmailField(max_length=100, unique=True)),
                ('direccion_per', models.CharField(blank=True, max_length=200, null=True)),
                ('documento_per', models.FileField(blank=True, null=True, upload_to='documentos_persona/')),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_ado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ado', models.DateField(auto_now_add=True)),
                ('documento_ado', models.FileField(blank=True, null=True, upload_to='documentos_adopcion/')),
                ('observacion_ado', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='Adopcion.mascota')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='Adopcion.persona')),
            ],
        ),
    ]
