# Generated by Django 5.1.13 on 2025-11-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcion',
            options={'ordering': ['-fecha_ado']},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre_mas']},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido_per']},
        ),
        migrations.AlterModelTable(
            name='adopcion',
            table='adopcion',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='mascota',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
